#!/bin/bash
# Setup test users in production for E2E testing
# This script creates test users via the API

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
E2E_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
API_BASE_URL="${API_BASE_URL:-https://tinev5iszf.execute-api.us-east-1.amazonaws.com}"
APP_BASE_URL="${APP_BASE_URL:-https://apps.quentinspencer.com/churchcoursetracker}"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Production E2E Test User Setup${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "API: ${BLUE}$API_BASE_URL${NC}"
echo -e "App: ${BLUE}$APP_BASE_URL${NC}"
echo ""

# Check for admin credentials to create test users
if [ -z "$ADMIN_USERNAME" ] || [ -z "$ADMIN_PASSWORD" ]; then
    echo -e "${YELLOW}Enter admin credentials to create test users:${NC}"
    read -p "Admin username: " ADMIN_USERNAME
    read -s -p "Admin password: " ADMIN_PASSWORD
    echo ""
fi

# Get admin token
echo -e "${GREEN}Authenticating as admin...${NC}"
AUTH_RESPONSE=$(curl -s -X POST "$API_BASE_URL/api/v1/auth/login" \
    -H "Content-Type: application/json" \
    -d "{\"username\": \"$ADMIN_USERNAME\", \"password\": \"$ADMIN_PASSWORD\"}")

ADMIN_TOKEN=$(echo "$AUTH_RESPONSE" | jq -r '.access_token // empty')

if [ -z "$ADMIN_TOKEN" ]; then
    echo -e "${RED}Failed to authenticate as admin${NC}"
    echo "$AUTH_RESPONSE"
    exit 1
fi

echo -e "${GREEN}✓ Authenticated${NC}"

# Generate random passwords
generate_password() {
    openssl rand -base64 12 | tr -d '/+=' | head -c 16
}

E2E_ADMIN_PASSWORD=$(generate_password)
E2E_STAFF_PASSWORD=$(generate_password)
E2E_VIEWER_PASSWORD=$(generate_password)

# Function to create or update user
create_user() {
    local username=$1
    local password=$2
    local full_name=$3
    local role=$4
    local email="${username}@e2e-test.local"

    echo -e "${GREEN}Creating user: $username ($role)...${NC}"

    # Try to create user
    RESPONSE=$(curl -s -X POST "$API_BASE_URL/api/v1/users/" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $ADMIN_TOKEN" \
        -d "{
            \"username\": \"$username\",
            \"email\": \"$email\",
            \"full_name\": \"$full_name\",
            \"password\": \"$password\",
            \"role\": \"$role\",
            \"is_active\": true
        }")

    # Check if user already exists (usually returns 400 or specific error)
    if echo "$RESPONSE" | grep -q "already exists\|duplicate\|unique"; then
        echo -e "  ${YELLOW}User already exists, updating password...${NC}"
        # Find user ID and update
        USER_LIST=$(curl -s "$API_BASE_URL/api/v1/users/" \
            -H "Authorization: Bearer $ADMIN_TOKEN")
        USER_ID=$(echo "$USER_LIST" | jq -r ".[] | select(.username==\"$username\") | .id")

        if [ -n "$USER_ID" ]; then
            curl -s -X PATCH "$API_BASE_URL/api/v1/users/$USER_ID" \
                -H "Content-Type: application/json" \
                -H "Authorization: Bearer $ADMIN_TOKEN" \
                -d "{\"password\": \"$password\", \"is_active\": true}" > /dev/null
            echo -e "  ${GREEN}✓ Updated${NC}"
        else
            echo -e "  ${RED}Could not find user to update${NC}"
        fi
    else
        echo -e "  ${GREEN}✓ Created${NC}"
    fi
}

# Create test users
create_user "e2e_admin" "$E2E_ADMIN_PASSWORD" "E2E Admin User" "admin"
create_user "e2e_staff" "$E2E_STAFF_PASSWORD" "E2E Staff User" "staff"
create_user "e2e_viewer" "$E2E_VIEWER_PASSWORD" "E2E Viewer User" "viewer"

# Generate .env.e2e file
ENV_FILE="$E2E_DIR/.env.e2e"
cat > "$ENV_FILE" << EOF
# E2E Test Environment Configuration
# Generated by setup-production-users.sh on $(date)
# DO NOT COMMIT THIS FILE

# Target environment
APP_BASE_URL=$APP_BASE_URL
API_BASE_URL=$API_BASE_URL

# Test user credentials
E2E_ADMIN_USERNAME=e2e_admin
E2E_ADMIN_PASSWORD=$E2E_ADMIN_PASSWORD

E2E_STAFF_USERNAME=e2e_staff
E2E_STAFF_PASSWORD=$E2E_STAFF_PASSWORD

E2E_VIEWER_USERNAME=e2e_viewer
E2E_VIEWER_PASSWORD=$E2E_VIEWER_PASSWORD

# Skip data loading/cleanup for production
E2E_SKIP_DATA_LOAD=true
E2E_SKIP_DATA_CLEANUP=true
EOF

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "Credentials saved to: ${BLUE}$ENV_FILE${NC}"
echo ""
echo -e "${YELLOW}To run E2E tests:${NC}"
echo "  cd tests/e2e && npm test"
echo ""
