#!/usr/bin/env python3
"""
Setup test users for E2E testing.

This script ensures admin, staff, and viewer test users exist in the local
SQLite database with known passwords, and generates a .env.e2e file.

For local development testing only.
"""

import os
import sys
import sqlite3
import hashlib
import secrets
from pathlib import Path

# For password hashing, use bcrypt directly
try:
    import bcrypt
except ImportError:
    print("bcrypt not installed. Installing...")
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "bcrypt", "-q"])
    import bcrypt


def get_password_hash(password: str) -> str:
    """Hash a password using bcrypt."""
    return bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()


def main():
    project_root = Path(__file__).parent.parent.parent.parent
    db_path = project_root / "backend" / "data" / "church_course_tracker.db"
    e2e_dir = project_root / "tests" / "e2e"
    env_file = e2e_dir / ".env.e2e"

    print("\n🔧 Setting up E2E test users in local SQLite database...\n")
    print(f"Database: {db_path}")

    if not db_path.exists():
        print(f"\n❌ Database not found: {db_path}")
        print("Run the backend first to create the database:")
        print("  cd backend && source venv/bin/activate && uvicorn app.main:app")
        sys.exit(1)

    # Fixed passwords for local development (easier debugging)
    passwords = {
        'admin': 'testpass123',
        'staff': 'testpass123',
        'viewer': 'testpass123',
    }

    test_users = {
        'admin': {
            'username': 'Admin',
            'email': 'admin@example.com',
            'full_name': 'System Admin',
            'role': 'admin',
        },
        'staff': {
            'username': 'staff',
            'email': 'test.staff@eastgate.church',
            'full_name': 'Test Staff User',
            'role': 'staff',
        },
        'viewer': {
            'username': 'viewer',
            'email': 'test.viewer@eastgate.church',
            'full_name': 'Test Viewer User',
            'role': 'viewer',
        },
    }

    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    try:
        for role, user_data in test_users.items():
            username = user_data['username']
            password = passwords[role]
            hashed = get_password_hash(password)

            # Check if user exists
            cursor.execute("SELECT id FROM users WHERE username = ?", (username,))
            existing = cursor.fetchone()

            if existing:
                print(f"  Updating password for '{username}'...")
                cursor.execute(
                    "UPDATE users SET hashed_password = ?, is_active = 1, role = ? WHERE username = ?",
                    (hashed, user_data['role'], username)
                )
            else:
                print(f"  Creating user '{username}'...")
                cursor.execute(
                    """INSERT INTO users (username, email, full_name, hashed_password, role, is_active)
                       VALUES (?, ?, ?, ?, ?, 1)""",
                    (username, user_data['email'], user_data['full_name'], hashed, user_data['role'])
                )

        conn.commit()
        print("\n✅ Test users configured successfully!\n")

        # Generate .env.e2e file
        env_content = f"""# E2E Test Environment Configuration
# Generated by setup-test-users.py
# DO NOT COMMIT THIS FILE

# Target environment (local development)
APP_BASE_URL=http://localhost:4200
API_BASE_URL=http://localhost:8000

# Test user credentials
E2E_ADMIN_USERNAME={test_users['admin']['username']}
E2E_ADMIN_PASSWORD={passwords['admin']}

E2E_STAFF_USERNAME={test_users['staff']['username']}
E2E_STAFF_PASSWORD={passwords['staff']}

E2E_VIEWER_USERNAME={test_users['viewer']['username']}
E2E_VIEWER_PASSWORD={passwords['viewer']}

# Skip CSV data loading (using existing SQLite data)
E2E_SKIP_DATA_LOAD=true
E2E_SKIP_DATA_CLEANUP=true
"""

        with open(env_file, 'w') as f:
            f.write(env_content)

        print(f"📝 Credentials saved to: {env_file}")
        print("\n" + "=" * 50)
        print("Test User Credentials:")
        print("=" * 50)
        for role, user_data in test_users.items():
            print(f"\n{role.upper()}:")
            print(f"  Username: {user_data['username']}")
            print(f"  Password: {passwords[role]}")
        print("\n" + "=" * 50)
        print("\nTarget: http://localhost:4200 (local)")
        print("=" * 50)
        print("\nTo run e2e tests:")
        print("  1. Start backend:  cd backend && source venv/bin/activate && uvicorn app.main:app --reload")
        print("  2. Start frontend: cd frontend/church-course-tracker && ng serve")
        print("  3. Run tests:      cd tests/e2e && npm test")

    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        conn.rollback()
        sys.exit(1)
    finally:
        conn.close()


if __name__ == "__main__":
    main()
