version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=h2://./data/church_course_tracker.db
      - SECRET_KEY=dev-secret-key-change-in-production
      - PLANNING_CENTER_API_URL=https://api.planningcenteronline.com
    volumes:
      - ../backend:/app
      - backend_data:/app/data
    depends_on:
      - db
    networks:
      - church-tracker-network

  # Frontend Service
  frontend:
    build:
      context: ../frontend/church-course-tracker
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - API_URL=http://localhost:8000/api/v1
    volumes:
      - ../frontend/church-course-tracker:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - church-tracker-network

  # H2 Database (if using H2 TCP server)
  db:
    image: oscarfonts/h2:latest
    ports:
      - "8082:8082"
    environment:
      - H2_OPTIONS=-web -webAllowOthers -tcp -tcpAllowOthers -browser
    volumes:
      - h2_data:/opt/h2-data
    networks:
      - church-tracker-network

  # Nginx Reverse Proxy (for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - church-tracker-network
    profiles:
      - production

volumes:
  backend_data:
  h2_data:

networks:
  church-tracker-network:
    driver: bridge
