"""Add course content management models

Revision ID: 7ddbf9820c62
Revises: 89341846d406
Create Date: 2025-09-22 20:40:26.041105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddbf9820c62'
down_revision = '89341846d406'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create new tables
    op.create_table('course_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_modules_id'), 'course_modules', ['id'], unique=False)
    
    op.create_table('course_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('DOCUMENT', 'VIDEO', 'AUDIO', 'IMAGE', 'EXTERNAL_LINK', 'EMBEDDED', name='contenttype'), nullable=False),
    sa.Column('storage_type', sa.Enum('DATABASE', 'S3', 'EXTERNAL', name='storagetype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('external_url', sa.String(length=1000), nullable=True),
    sa.Column('embedded_content', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_content_id'), 'course_content', ['id'], unique=False)
    
    op.create_table('content_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.String(length=20), nullable=False),
    sa.Column('access_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['course_content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_access_logs_id'), 'content_access_logs', ['id'], unique=False)
    
    op.create_table('content_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('change_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['course_content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_audit_logs_id'), 'content_audit_logs', ['id'], unique=False)
    
    # Add columns to existing courses table using batch mode for SQLite
    with op.batch_alter_table('courses') as batch_op:
        batch_op.add_column(sa.Column('content_unlock_mode', sa.String(length=20), nullable=False, server_default='immediate'))
        batch_op.add_column(sa.Column('max_file_size_mb', sa.Integer(), nullable=False, server_default='1024'))
    
    # Remove the problematic foreign key constraints that were auto-generated
    # These seem to be referencing non-existent columns
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop columns from courses table using batch mode
    with op.batch_alter_table('courses') as batch_op:
        batch_op.drop_column('max_file_size_mb')
        batch_op.drop_column('content_unlock_mode')
    
    # Drop tables in reverse order
    op.drop_index(op.f('ix_content_audit_logs_id'), table_name='content_audit_logs')
    op.drop_table('content_audit_logs')
    op.drop_index(op.f('ix_content_access_logs_id'), table_name='content_access_logs')
    op.drop_table('content_access_logs')
    op.drop_index(op.f('ix_course_content_id'), table_name='course_content')
    op.drop_table('course_content')
    op.drop_index(op.f('ix_course_modules_id'), table_name='course_modules')
    op.drop_table('course_modules')
    # ### end Alembic commands ###
